
#Fishing
[fishing]
	#0 means the rods will break and the fishing module won't try to find a replacement in storage (server side only)
	#Range: 0 ~ 64
	remainingUsesBeforeRemoval = 0
	#The higher, the more frequent the fishing module will fish items (server side only)
	#Range: 1.0E-15 ~ 100.0
	speedMultiplier = 1.0

#Boat battery
[boatBattery]
	#The total amount of energy a single boat battery can hold at once
	#Range: > 1
	maxEnergy = 25000

#Energy Unloader
[energyUnloader]
	#The maximum energy amount that can be hold
	#Range: > 1
	maxEnergy = 5000
	#The energy amount that can be received in a tick (in RF/FE)
	#Range: > 1
	pullAmount = 200
	#The energy amount that can be sent in a tick (in RF/FE)
	#Range: > 1
	sendAmount = 200

#Energy Unloader
[energyLoader]
	#The maximum energy amount that can be hold
	#Range: > 1
	maxEnergy = 5000
	#The energy amount that can be received in a tick (in RF/FE)
	#Range: > 1
	pullAmount = 200
	#The energy amount that can be sent in a tick (in RF/FE)
	#Range: > 1
	sendAmount = 200

#Fluid Tank
[fluidTank]
	#The fluid capacity of the on-board fluid tank
	#Range: > 1
	tankCapacity = 10000

#Fluid loader
[fluidLoader]
	#The total amount of fluid the fluid loader can hold at once (in mB)
	#Range: > 1
	sendAmount = 200
	#The total amount of fluid the fluid loader can hold at once (in mB)
	#Range: > 1
	capacity = 5000

#Fluid unloader
[fluidUnloader]
	#The total amount of fluid a single fluid boat unloader can extract from neighboring entities (per tick)
	#Range: > 1
	pullAmount = 200
	#The total amount of fluid the fluid unloader can hold at once (in mB)
	#Range: > 1
	capacity = 5000

#Dispenser module
[dispenserModule]
	#Choose to either allow select items or disallow select items
	configMode = "disallow"
	#List of item IDs to allow/disallow, must match '^([a-z_]+:)?([a-z_]+)(\/\d+)?$' (domain:name/metadata with 'domain:' and 'metadata' optional)
	items = []

#Chunk Loader
[chunkLoader]
	#Do you want to allow the chunk loader module on your server?
	allowed = true

#Furnace boats
[furnaceBoats]
	#Time in ticks between two packets describing the state of furnaces (smoker, blaster, furnace) inside boats. Only graphical. -1 means no update
	#Range: > -1
	stateUpdateInterval = 20

#Misc
[misc]
	#Hide the Patreon hook?
	hidePatreonHook = false

